services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  uebungsprojekt:
    image: uebungsprojekt
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080